#!/bin/bash
# Demo seed data — creates 2 counts per facility for biweekly + monthly,
# with pulls, receipts, and a transfer interleaved so Reconcile shows activity.
# Run this against a fresh server (rate limit: 20 POSTs/IP/hour).

BASE="${BASE:-http://localhost:3100}"

post() {
  local path="$1" body="$2"
  printf "→ %s " "$path"
  local resp
  resp=$(curl -s -X POST "$BASE$path" -H "Content-Type: application/json" -d "$body")
  echo "$resp"
}

# ───────────── SATC biweekly ─────────────
post /api/count '{"facility":"SATC","count_type":"biweekly","submitted_by":"Jaime Garcia","items":{"reels":{"hawk_touch":{"storage":6,"display":3},"hawk_tour_rpet":{"storage":8,"display":2},"rpm_blast":{"storage":4,"display":1},"lynx_tour":{"storage":5,"display":2},"polytour_pro_yellow":{"storage":3,"display":1}},"multifilament":{"velocity_mlt":{"storage":3,"display":1}},"ball_cases":{"full_cases":{"storage":12,"display":0},"open_cans":{"storage":0,"display":4}},"concessions":{"water_cases":{"storage":8,"display":2}},"supplies":{"toilet_paper":{"storage":15,"display":0},"hand_soap":{"storage":4,"display":2}},"gut_strings":{"synthetic_gut_head":{"storage":3,"display":1},"touch_vs":{"storage":1,"display":0}}}}'
sleep 2
post /api/pull '{"facility":"SATC","category":"reels","item":"rpm_blast","quantity":3,"pulled_by":"Maria Lopez","type":"pull","notes":"Weekend restock"}'
post /api/pull '{"facility":"SATC","category":"reels","item":"hawk_touch","quantity":6,"pulled_by":"Jaime Garcia","type":"receipt","notes":"PO #4821 from distributor"}'
post /api/pull '{"facility":"SATC","category":"ball_cases","item":"full_cases","quantity":5,"pulled_by":"Jaime Garcia","type":"receipt","notes":"Penn shipment"}'
sleep 2
post /api/count '{"facility":"SATC","count_type":"biweekly","submitted_by":"Jaime Garcia","items":{"reels":{"hawk_touch":{"storage":9,"display":2},"hawk_tour_rpet":{"storage":7,"display":2},"rpm_blast":{"storage":1,"display":2},"lynx_tour":{"storage":4,"display":2},"polytour_pro_yellow":{"storage":3,"display":1}},"multifilament":{"velocity_mlt":{"storage":3,"display":0}},"ball_cases":{"full_cases":{"storage":16,"display":0},"open_cans":{"storage":0,"display":3}},"concessions":{"water_cases":{"storage":5,"display":1}},"supplies":{"toilet_paper":{"storage":13,"display":0},"hand_soap":{"storage":4,"display":2}},"gut_strings":{"synthetic_gut_head":{"storage":3,"display":1},"touch_vs":{"storage":1,"display":0}}}}'

# ───────────── Pharr biweekly ─────────────
post /api/count '{"facility":"Pharr","count_type":"biweekly","submitted_by":"Alex Chen","items":{"reels":{"hawk_touch":{"storage":4,"display":2},"hawk_tour_rpet":{"storage":3,"display":1},"rpm_blast":{"storage":2,"display":1},"lynx_tour":{"storage":3,"display":2},"polytour_pro_yellow":{"storage":4,"display":2},"polytour_pro_blue":{"storage":3,"display":1}},"multifilament":{"velocity_mlt":{"storage":2,"display":1}},"ball_cases":{"full_cases":{"storage":8,"display":0},"open_cans":{"storage":0,"display":2}},"concessions":{"water_cases":{"storage":4,"display":1}},"supplies":{"toilet_paper":{"storage":10,"display":0},"hand_soap":{"storage":3,"display":1}},"gut_strings":{"synthetic_gut_head":{"storage":2,"display":1},"touch_vs":{"storage":0,"display":0}}}}'
sleep 2
post /api/pull '{"facility":"Pharr","category":"multifilament","item":"velocity_mlt","quantity":10,"pulled_by":"Alex Chen","type":"receipt","notes":"Restock order"}'
post /api/transfer '{"from_facility":"Pharr","to_facility":"Wilco","category":"reels","item":"polytour_pro_yellow","quantity":2,"transferred_by":"Alex Chen","notes":"Wilco was out"}'
sleep 2
post /api/count '{"facility":"Pharr","count_type":"biweekly","submitted_by":"Alex Chen","items":{"reels":{"hawk_touch":{"storage":3,"display":2},"hawk_tour_rpet":{"storage":3,"display":0},"rpm_blast":{"storage":1,"display":1},"lynx_tour":{"storage":3,"display":1},"polytour_pro_yellow":{"storage":2,"display":2},"polytour_pro_blue":{"storage":3,"display":1}},"multifilament":{"velocity_mlt":{"storage":10,"display":1}},"ball_cases":{"full_cases":{"storage":6,"display":0},"open_cans":{"storage":0,"display":3}},"concessions":{"water_cases":{"storage":2,"display":1}},"supplies":{"toilet_paper":{"storage":9,"display":0},"hand_soap":{"storage":3,"display":1}},"gut_strings":{"synthetic_gut_head":{"storage":1,"display":1},"touch_vs":{"storage":0,"display":0}}}}'

# ───────────── Wilco biweekly ─────────────
post /api/count '{"facility":"Wilco","count_type":"biweekly","submitted_by":"Sam Patel","items":{"reels":{"hawk_touch":{"storage":3,"display":1},"hawk_tour_rpet":{"storage":4,"display":1},"rpm_blast":{"storage":2,"display":0},"lynx_tour":{"storage":2,"display":1},"polytour_pro_yellow":{"storage":1,"display":0},"lynx_touch":{"storage":2,"display":1}},"multifilament":{"velocity_mlt":{"storage":1,"display":0},"reflex_mlt":{"storage":2,"display":1}},"ball_cases":{"full_cases":{"storage":6,"display":0},"open_cans":{"storage":0,"display":2}},"concessions":{"water_cases":{"storage":5,"display":2}},"supplies":{"toilet_paper":{"storage":8,"display":0},"hand_soap":{"storage":2,"display":1}},"gut_strings":{"synthetic_gut_head":{"storage":1,"display":0},"touch_vs":{"storage":0,"display":0}}}}'
sleep 2
post /api/pull '{"facility":"Wilco","category":"reels","item":"lynx_tour","quantity":2,"pulled_by":"Sam Patel","type":"pull","notes":"Monday morning restock"}'
sleep 2
post /api/count '{"facility":"Wilco","count_type":"biweekly","submitted_by":"Sam Patel","items":{"reels":{"hawk_touch":{"storage":2,"display":1},"hawk_tour_rpet":{"storage":3,"display":1},"rpm_blast":{"storage":2,"display":0},"lynx_tour":{"storage":0,"display":2},"polytour_pro_yellow":{"storage":1,"display":2},"lynx_touch":{"storage":2,"display":0}},"multifilament":{"velocity_mlt":{"storage":1,"display":0},"reflex_mlt":{"storage":2,"display":1}},"ball_cases":{"full_cases":{"storage":5,"display":0},"open_cans":{"storage":0,"display":2}},"concessions":{"water_cases":{"storage":3,"display":1}},"supplies":{"toilet_paper":{"storage":7,"display":0},"hand_soap":{"storage":2,"display":1}},"gut_strings":{"synthetic_gut_head":{"storage":1,"display":0},"touch_vs":{"storage":0,"display":0}}}}'

# ───────────── SATC monthly ─────────────
post /api/count '{"facility":"SATC","count_type":"monthly","submitted_by":"Jaime Garcia","items":{"prime_tour_grips":{"white":{"storage":25,"display":6},"black":{"storage":22,"display":5},"pink":{"storage":14,"display":3},"blue":{"storage":18,"display":4}},"pro_grips":{"total":{"storage":28,"display":5}},"wristbands":{"2_5in_black":{"storage":10,"display":4},"2_5in_white":{"storage":8,"display":3},"5in_black":{"storage":6,"display":2},"5in_white":{"storage":5,"display":2}},"headbands":{"black":{"storage":12,"display":3},"white":{"storage":10,"display":2}},"rackets":{"boom_2026":{"storage":4,"display":2},"speed_2026":{"storage":5,"display":2},"speed_legend":{"storage":2,"display":1},"gravity":{"storage":3,"display":1},"radical":{"storage":2,"display":1},"extreme":{"storage":1,"display":1},"boom_2024":{"storage":2,"display":0},"boom_neon":{"storage":1,"display":1},"boom_ashe":{"storage":0,"display":1}}}}'
sleep 2
post /api/pull '{"facility":"SATC","category":"prime_tour_grips","item":"pink","quantity":12,"pulled_by":"Maria Lopez","type":"receipt","notes":"Grip refill shipment"}'
sleep 2
post /api/count '{"facility":"SATC","count_type":"monthly","submitted_by":"Jaime Garcia","items":{"prime_tour_grips":{"white":{"storage":20,"display":5},"black":{"storage":18,"display":4},"pink":{"storage":24,"display":2},"blue":{"storage":15,"display":3}},"pro_grips":{"total":{"storage":22,"display":4}},"wristbands":{"2_5in_black":{"storage":9,"display":3},"2_5in_white":{"storage":7,"display":3},"5in_black":{"storage":5,"display":2},"5in_white":{"storage":4,"display":2}},"headbands":{"black":{"storage":11,"display":3},"white":{"storage":9,"display":2}},"rackets":{"boom_2026":{"storage":3,"display":2},"speed_2026":{"storage":4,"display":2},"speed_legend":{"storage":2,"display":1},"gravity":{"storage":3,"display":1},"radical":{"storage":2,"display":1},"extreme":{"storage":1,"display":1},"boom_2024":{"storage":2,"display":0},"boom_neon":{"storage":1,"display":1},"boom_ashe":{"storage":0,"display":1}}}}'

# ───────────── Pharr monthly ─────────────
post /api/count '{"facility":"Pharr","count_type":"monthly","submitted_by":"Alex Chen","items":{"prime_tour_grips":{"white":{"storage":18,"display":4},"black":{"storage":16,"display":3},"pink":{"storage":10,"display":2},"blue":{"storage":12,"display":3}},"pro_grips":{"total":{"storage":20,"display":4}},"wristbands":{"2_5in_black":{"storage":7,"display":2},"2_5in_white":{"storage":6,"display":2},"5in_black":{"storage":4,"display":1},"5in_white":{"storage":3,"display":1}},"headbands":{"black":{"storage":8,"display":2},"white":{"storage":6,"display":2}},"rackets":{"boom_2026":{"storage":2,"display":1},"speed_2026":{"storage":3,"display":1},"speed_legend":{"storage":1,"display":1},"gravity":{"storage":2,"display":1},"radical":{"storage":1,"display":1},"extreme":{"storage":1,"display":0},"boom_2024":{"storage":1,"display":0},"boom_neon":{"storage":0,"display":1},"boom_ashe":{"storage":1,"display":0}}}}'
sleep 2
post /api/count '{"facility":"Pharr","count_type":"monthly","submitted_by":"Alex Chen","items":{"prime_tour_grips":{"white":{"storage":15,"display":3},"black":{"storage":14,"display":3},"pink":{"storage":9,"display":2},"blue":{"storage":10,"display":2}},"pro_grips":{"total":{"storage":17,"display":3}},"wristbands":{"2_5in_black":{"storage":6,"display":2},"2_5in_white":{"storage":5,"display":2},"5in_black":{"storage":3,"display":1},"5in_white":{"storage":3,"display":1}},"headbands":{"black":{"storage":7,"display":2},"white":{"storage":5,"display":2}},"rackets":{"boom_2026":{"storage":2,"display":1},"speed_2026":{"storage":3,"display":1},"speed_legend":{"storage":1,"display":1},"gravity":{"storage":2,"display":1},"radical":{"storage":1,"display":1},"extreme":{"storage":1,"display":0},"boom_2024":{"storage":1,"display":0},"boom_neon":{"storage":0,"display":1},"boom_ashe":{"storage":1,"display":0}}}}'

# ───────────── Wilco monthly ─────────────
post /api/count '{"facility":"Wilco","count_type":"monthly","submitted_by":"Sam Patel","items":{"prime_tour_grips":{"white":{"storage":14,"display":3},"black":{"storage":12,"display":2},"pink":{"storage":8,"display":2},"blue":{"storage":10,"display":2}},"pro_grips":{"total":{"storage":15,"display":3}},"wristbands":{"2_5in_black":{"storage":5,"display":2},"2_5in_white":{"storage":4,"display":2},"5in_black":{"storage":3,"display":1},"5in_white":{"storage":2,"display":1}},"headbands":{"black":{"storage":6,"display":2},"white":{"storage":5,"display":1}},"rackets":{"boom_2026":{"storage":1,"display":1},"speed_2026":{"storage":2,"display":1},"speed_legend":{"storage":1,"display":0},"gravity":{"storage":1,"display":1},"radical":{"storage":1,"display":0},"extreme":{"storage":0,"display":1},"boom_2024":{"storage":1,"display":0},"boom_neon":{"storage":1,"display":0},"boom_ashe":{"storage":0,"display":1}}}}'
sleep 2
post /api/count '{"facility":"Wilco","count_type":"monthly","submitted_by":"Sam Patel","items":{"prime_tour_grips":{"white":{"storage":12,"display":2},"black":{"storage":10,"display":2},"pink":{"storage":7,"display":1},"blue":{"storage":9,"display":2}},"pro_grips":{"total":{"storage":13,"display":2}},"wristbands":{"2_5in_black":{"storage":4,"display":2},"2_5in_white":{"storage":4,"display":1},"5in_black":{"storage":2,"display":1},"5in_white":{"storage":2,"display":1}},"headbands":{"black":{"storage":5,"display":2},"white":{"storage":4,"display":1}},"rackets":{"boom_2026":{"storage":1,"display":1},"speed_2026":{"storage":2,"display":1},"speed_legend":{"storage":1,"display":0},"gravity":{"storage":1,"display":1},"radical":{"storage":1,"display":0},"extreme":{"storage":0,"display":1},"boom_2024":{"storage":1,"display":0},"boom_neon":{"storage":1,"display":0},"boom_ashe":{"storage":0,"display":1}}}}'

echo
echo "Done."
